services:
  - type: web
    name: content-resourcer-worker
    runtime: node
    plan: starter
    buildCommand: npm install && npm run build -w @content-resourcer/db && npm run build -w @content-resourcer/worker
    startCommand: npm run start -w @content-resourcer/worker
    envVars:
      - key: NODE_VERSION
        value: "20"
